import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../lib/api.js';

const LABEL = { draft:'Draft', approved:'Approved', submitted:'Submitted', interviewing:'Interviewing', offered:'Offered', placed:'Placed', rejected:'Rejected', withdrawn:'Withdrawn' };
export default function WizmatchDeliveryBoardPage() {
  const [items,setItems]=useState([]); const [analytics,setAnalytics]=useState(null); const [capabilities,setCapabilities]=useState({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const access=await apiFetch('/api/wizmatch/staffing/access');const caps=access.capabilities||{};setCapabilities(caps);const board=await apiFetch('/api/wizmatch/staffing/delivery-board');const metrics=caps.viewCommercial?await apiFetch('/api/wizmatch/staffing/analytics'):null;setItems(board.items||[]);setAnalytics(metrics);}catch(e){setItems([]);setAnalytics(null);setError(e.message||'Delivery board could not be loaded.');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  async function run(item,action){setBusy(item.id);setError('');try{
    if(action==='approve') await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/approve`,{method:'POST'});
    if(action==='sent'){const name=prompt('Named client recipient');if(!name)return;const email=prompt('Recipient email (optional)')||'';await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/record-sent`,{method:'POST',body:JSON.stringify({recipients:[{name,email}],nextActionDueAt:new Date(Date.now()+86400000).toISOString()})});}
    if(action==='interview'){const scheduledAt=prompt('Interview date/time (ISO or local date)');if(!scheduledAt)return;await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/interviews`,{method:'POST',body:JSON.stringify({scheduledAt,nextAction:'Collect interview feedback',nextActionDueAt:new Date(new Date(scheduledAt).getTime()+7200000).toISOString()})});}
    if(action==='offer'){const amount=Number(prompt('Offer amount in smallest currency unit / whole INR')||0);await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/offers`,{method:'POST',body:JSON.stringify({amount,currency:'INR',period:'annual',status:'draft'})});}
    if(action==='accept') await apiFetch(`/api/wizmatch/staffing/offers/${item.latest_offer_id}/status`,{method:'PUT',body:JSON.stringify({status:'accepted'})});
    if(action==='place'){const model=(prompt('Placement model: permanent or contract','permanent')||'permanent').toLowerCase();if(!['permanent','contract'].includes(model))throw new Error('Placement model must be permanent or contract.');const originalAmount=Number(prompt(model==='permanent'?'Permanent fee amount':'Contract bill rate')||0);const payload={offerId:item.latest_offer_id,model,originalAmount,currency:'INR',period:model==='contract'?'hourly':'one_time',feeAmount:model==='permanent'?originalAmount:null,billAmount:model==='contract'?originalAmount:null,startDate:new Date().toISOString().slice(0,10)};if(model==='contract'){payload.loadedCost=Number(prompt('Loaded cost for the same period')||0);payload.payAmount=payload.loadedCost;const margin=originalAmount>0?((originalAmount-payload.loadedCost)/originalAmount)*100:0;if(margin<20)payload.marginExceptionReason=prompt(`Gross margin is ${margin.toFixed(1)}%. Record the approved exception reason`)||'';}await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/placement`,{method:'POST',body:JSON.stringify(payload)});}
    if(action==='withdraw'){const reason=prompt('Why is this submission being withdrawn?');if(!reason)return;await apiFetch(`/api/wizmatch/staffing/submissions/${item.id}/withdraw`,{method:'POST',body:JSON.stringify({reason})});}
    await load();
  }catch(e){setError(e.message||'Delivery action could not be recorded.');}finally{setBusy('');}}
  const money=analytics?.commercial||{}; const exceptions=analytics?.exceptions||{};
  return <div className="p-6 space-y-5"><div className="flex justify-between items-start"><div><h1 className="text-[20px] font-bold text-neutral-900">Submissions & Delivery</h1><p className="text-[12.5px] text-neutral-500 mt-1">Consent → approval → manual delivery record → interview → offer → placement. This page never sends automatically.</p></div><button className="btn-standard btn-compact" onClick={load}><RefreshCw className="w-3.5 h-3.5"/> Refresh</button></div>
  {capabilities.viewCommercial&&<><div className="grid md:grid-cols-5 gap-3">{[['Starts',money.starts||0],['Gross margin',money.gross_margin||0],['Invoiced',money.invoiced||0],['Collected',money.collected||0],['Avg. time to fill',analytics?.timeToFill?.average_days?`${analytics.timeToFill.average_days} days`:'—']].map(([label,value])=><div className="card p-4" key={label}><div className="text-[11px] text-neutral-500 uppercase">{label}</div><div className="text-xl font-bold text-neutral-900 mt-1">{value}</div></div>)}</div><div className="rounded-md border border-warning-200 bg-warning-50 p-3 text-[12.5px] text-warning-800"><ShieldCheck className="w-4 h-4 inline mr-2"/>Exceptions: {exceptions.overdue_submissions||0} overdue · {exceptions.missing_next_action||0} missing next action.</div></>}
  {error&&<div role="alert" className="border border-danger-200 bg-danger-50 text-danger-700 rounded-md p-3">{error} <button className="underline font-semibold ml-2" onClick={load}>Retry</button></div>}
  {loading?<div className="card p-8 text-center text-neutral-400">Loading delivery records…</div>:<div className="card overflow-hidden"><table className="table-fluent"><thead><tr><th>Candidate</th><th>Requirement</th><th>Consent</th><th>Status</th><th>Delivery evidence</th><th>Next action</th></tr></thead><tbody>{!items.length?<tr><td colSpan="6" className="text-center py-8 text-neutral-400">No submission drafts yet.</td></tr>:items.map(item=><tr key={item.id}><td className="font-semibold">{[item.first_name,item.last_name].filter(Boolean).join(' ')}</td><td>{item.requirement_title}<div className="text-[11px] text-neutral-500">{item.company_name}</div></td><td><span className={item.consent_status==='granted'?'badge-success':'badge-warning'}>{item.consent_status||'not linked'}</span></td><td><span className="badge-info">{LABEL[item.status]||item.status}</span></td><td className="text-[11.5px]">{item.resend_count||0} resends · {item.interview_count||0} interviews · offer {item.offer_revision||'—'}</td><td><div className="flex flex-wrap gap-1">{capabilities.approveSubmissions&&item.status==='draft'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'approve')}>Approve</button>}{capabilities.approveSubmissions&&item.status==='approved'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'sent')}>Record sent</button>}{capabilities.operateDelivery&&item.status==='submitted'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'interview')}>Add interview</button>}{capabilities.manageOffers&&item.status==='interviewing'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'offer')}>Add offer</button>}{capabilities.manageOffers&&item.status==='offered'&&item.offer_status!=='accepted'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'accept')}>Record accepted</button>}{capabilities.manageFinance&&item.status==='offered'&&item.offer_status==='accepted'&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'place')}>Create placement</button>}{capabilities.approveSubmissions&&!['placed','withdrawn','closed'].includes(item.status)&&<button disabled={busy===item.id} className="btn-standard btn-compact" onClick={()=>run(item,'withdraw')}>Withdraw</button>}</div></td></tr>)}</tbody></table></div>}</div>;
}
